### ISSUE TITLE
使用私有域名，不能进行harbor镜像的同步操作

### ISSUE THREAD

**Issue by liuyp2018** [QingCloudAppcenter/Harbor#23]
harbor仓库使用私有域名地址时，在另一个harbor仓库中，创建同步目标时，无法解析到该域名，即便在该harbor的主服务节点上的hosts中进行了该私有域名的解析配置
<img width="404" alt="1" src="https://user-images.githubusercontent.com/36271543/70416475-1e11f300-1a9a-11ea-94c1-204638f1676a.png">

**Comment by hlwanghl** [comment]
需要是全局 DNS 配置的域名，用户没法去改机器上的 hosts 文件。
