### ISSUE TITLE
删除某主服务节点操作后，上传镜像至harbor，有时会出现镜像不全的问题

### ISSUE THREAD

**Issue by liuyp2018** [QingCloudAppcenter/Harbor#25]
删除/添加主服务节点，或者某一个主服务的网络异常后，上传镜像至harbor，有时会出现如下提示信息：

root@i-w5nv52q2:/home/ubuntu# docker push 192.168.0.248/library/hello-world:v12
The push refers to repository [192.168.0.248/library/hello-world]
af0b15c8625b: Layer already exists 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the 192.168.0.248 registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
v12: digest: sha256:161589c3bb703a6993a41015b0016cd2234af59e4d916559ff46c117fb849d0f size: 214

登录控制台，查看该上传的镜像，构建历史无法查看，界面一直处于加载状态

**Comment by liuyp2018** [comment]
<img width="593" alt="3" src="https://user-images.githubusercontent.com/36271543/70603049-bb069480-1c30-11ea-81ec-cbd904e7e8e0.png">

**Comment by taker-w** [comment]
retag the same image multi times may cause that

**Comment by liuyp2018** [comment]
经验证，未修改镜像反复上传同一个镜像，会出现该问题；修改镜像之后再上传镜像，未出现该问题。
