### ISSUE TITLE
2个主服务节点的集群，某一主服务节点网络异常后，harbor清理垃圾和漏洞扫描时，提示Internal Server Error

### ISSUE THREAD

**Issue by liuyp2018** [QingCloudAppcenter/Harbor#30]
集群包含2个主服务节点，在其中一个主服务节点中，利用iptables命令模拟网络异常，异常后，在harbor界面中，进行漏洞扫描和清理垃圾操作，提示Internal Server Error；
但，通过命令进行上传和拉取镜像功能正常。

**Comment by spwangxp** [comment]
经过测试，功能正常。测试集群 cl-338lpprf 
测试方法：1：创建集群，进行镜像推送扫描GC等操作，正常。 2：对其中一台web节点进行断网模拟。command: iptables -A INPUT -s 192.0.0.0/8 -j REJECT
表现为无法被ping通。3：进行镜像的基础操作正常，web界面运行良好，镜像扫描/GC均正常。

**Comment by liuyp2018** [comment]
之前出现一次，后再次测试，未出现该情况，暂时关闭该问题。
