### ISSUE TITLE
支持通过浏览器直接查看历史日志文件

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/Harbor#33]
版本 `Harbor 1.9.3 - QingCloud 1.9.0.RC1`

希望可以直接通过浏览器快速查看日志，目前的历史日志需要下载到本地一个一个打开查看。

![image](https://user-images.githubusercontent.com/4861515/71757830-f9ac0980-2ed3-11ea-89d2-5b181e985c9e.png)

**Comment by hlwanghl** [comment]
研究一下看看，能不能 rotate 成类似 Kafka 的效果：

kafka
```
db.log.2020-01-01
db.log.2020-01-02
db.log.2020-01-03
db.log.2020-01-04
db.log
```

或者

kafka manager
```
db-2020-01-01.log
db-2020-01-02.log
db-2020-01-03log
db-2020-01-04.log
db.log
```

![image](https://user-images.githubusercontent.com/4861515/71758092-8952b780-2ed6-11ea-846a-1d35707c38e4.png)

**Comment by hlwanghl** [comment]
kafka 的可以直接在浏览器里直接查看

**Comment by spwangxp** [comment]
嗯嗯，不压缩的话应该就是类似于Kafka了

**Comment by spwangxp** [comment]
目前这种是支持在线查看（实测30M大小还可以在线查看）。但是如果文件过大，默认还是下载。

**Comment by hlwanghl** [comment]
> 目前这种是支持在线查看（实测30M大小还可以在线查看）。但是如果文件过大，默认还是下载。

文件大小要控制一下，目前是 2M，建议进一步限制到 1M，然后增大文件数量，比如 100 个文件。

**Comment by spwangxp** [comment]
好的，但是这个大小设置并不会影响到最终的文件大小，也就是说最后的文件如果很大，caddy还是默认下载。

**Comment by hlwanghl** [comment]
> 好的，但是这个大小设置并不会影响到最终的文件大小，也就是说最后的文件如果很大，caddy还是默认下载。

那这个设置是干什么用的？我们的目的是方便用户自己去查看，避免我们上去帮用户查。如果中间有不方便的地方，要尽量去克服。

**Comment by spwangxp** [comment]
这个大小设置是轮转要求，并非限制了文件的生成大小。

**Comment by hlwanghl** [comment]
> 这个大小设置是轮转要求，并非限制了文件的生成大小。

怎么达到我们的目的？

**Comment by spwangxp** [comment]
您说的在线预览是可以的，举个例子，如果某天的web.log文件达到了50M，那就需要下载看了。我会去查一下caddy是否有这方面的限制。
